### ISSUE TITLE
Bug: Yaml Unmarshal and Marshal float values to integer values 

### ISSUE THREAD

**Issue by mahjonp** [PingCAP-QE/Naglfar#126]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```yaml
apiVersion: naglfar.pingcap.com/v1
kind: TestClusterTopology
metadata:
  name: tidb-cluster
  namespace: {{workflow.name}}
spec:
  resourceRequest: tidb-cluster
  tidbCluster:
    serverConfigs:
      tidb: |-
        mem-quota-query: 34359738368
        tikv-client.copr-cache.capacity-mb: 0.0
```

### 2. What did you expect to see? (Required)

OK

### 3. What did you see instead (Required)

topology.yaml

```yaml
mem-quota-query: 34359738368
tikv-client.copr-cache.capacity-mb: 0
```
