### ISSUE TITLE
feature: inject cluster endpoint through environment variables on workload jobs

### ISSUE THREAD

**Issue by mahjonp** [PingCAP-QE/Naglfar#39]
Using env variables enhances the usability of Naglfar compare to an SDK(currently)

For example, the workload can get a standard cluster's service endpoint from the environment variables(like $cluster_tidb$index)

```yaml
apiVersion: naglfar.pingcap.com/v1
kind: TestWorkload
metadata:
  name: naglfar-demo
  namespace: naglfar-test
spec:
  clusterTopologies:
    - name: tidb-cluster
      aliasName: standard
  workloads:
    - name: naglfar-demo
      dockerContainer:
        name: naglfar-demo
        resourceRequest:
          name: tidb-cluster
          node: n3
        image: "severalnines/sysbench"
        command:
          - /bin/sh
          - -c
          - |
            set -ex
            tidb=`echo $standard_tidb0 | awk -F ":" '{print $1}'`
            sysbench oltp_point_select prepare \
              --mysql-host=$tidb \
              --mysql-port=4000 \
              --mysql-user=root \
              --db-driver=mysql \
              --tables=10 \
              --table-size=10000 \
              --mysql-db=test \
              --threads=100

            sysbench oltp_point_select run \
              --mysql-host=$tidb \
              --mysql-port=4000 \
              --mysql-user=root \
              --db-driver=mysql \
              --tables=10 \
              --table-size=10000 \
              --mysql-db=test \
              --threads=100 \
              --time=600 --report-interval=10
```
