### ISSUE TITLE
Deletion of TCT is blocked when specification refers not exist nodes

### ISSUE THREAD

**Issue by mahjonp** [PingCAP-QE/Naglfar#80]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. apply trr.yaml:

```yaml
apiVersion: naglfar.pingcap.com/v1
kind: TestResourceRequest
metadata:
  name: tidb-cluster
  namespace: mahjonp
spec:
  machines:
    - name: m1
  items:
    - name: control
      spec:
        memory: 8GB
        cores: 4
        machine: m1
```
2. apply tct.yaml
```yaml
apiVersion: naglfar.pingcap.com/v1
kind: TestClusterTopology
metadata:
  name: tidb-cluster
  namespace: mahjonp
spec:
  resourceRequest: tidb-cluster
  tidbCluster:
    serverConfigs:
      tidb: |-
#        log.slow-threshold: 0
#      tikv: |-
#        readpool.storage.use-unified-pool: false
#        readpool.coprocessor.use-unified-pool: true
#      pd: |-
#        schedule.leader-schedule-limit: 4
#        schedule.region-schedule-limit: 2048
#        schedule.replica-schedule-limit: 64
    version:
      version: v4.0.8
#      tikvDownloadURL: http://fileserver.pingcap.net/download/builds/pingcap/tikv/164eb3d2dc94064f80b3ad3f6ae21cb071aaf36d/centos7/tikv-server.tar.gz
#      tidbDownloadURL: http://fileserver.pingcap.net/download/builds/pingcap/tidb/22feeb4aef750724f9f1321267a6bd5a661eb5e7/centos7/tidb-server.tar.gz
    control: n1
    tikv:
      - host: n1
        port: 20160
        statusPort: 20180
        deployDir: /disk1/deploy/tikv-20160
        dataDir: /disk1/data/tikv-20160
        logDir: /disk1/deploy/tikv-20160/log
#      - host: tikv-2
#        port: 20160
#        statusPort: 20180
#        deployDir: /disk1/deploy/tikv-20160
#        dataDir: /disk1/data/tikv-20160
#        logDir: /disk1/deploy/tikv-20160/log
#      - host: tikv-3
#        port: 20160
#        statusPort: 20180
#        deployDir: /disk1/deploy/tikv-20160
#        dataDir: /disk1/data/tikv-20160
#        logDir: /disk1/deploy/tikv-20160/log
    tidb:
      - host: n1
        deployDir: /disk1/deploy/tidb-4000
    pd:
      - host: n1
        deployDir: /disk1/deploy/pd-2379
        dataDir: /disk1/data/pd-2379
        logDir: /disk1/deploy/pd-2379/log
    monitor:
      - host: n1
        deployDir: /disk1/deploy/prometheus-8249
        dataDir: /disk1/deploy/prometheus-8249/data
    grafana:
      - host: n1
        deployDir: /disk1/deploy/grafana-3000
```
3. delete tct.yaml

### 2. What did you expect to see? (Required)

The tct is deleteded

### 3. What did you see instead (Required)

The deletion of tct is blocked because of below error:

```
2020-12-21T07:41:08.650Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "testclustertopology", "request": "mahjonp/tidb-cluster", "error": "control node not found: `n1`"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
```
